CREATE TABLE Artista(id INTEGER PRIMARY KEY, nombre VARCHAR(50) NOT NULL,edad INTEGER NOT NULL, sexo VARCHAR(50) NOT NULL);
CREATE TABLE Email(email VARCHAR(50) PRIMARY KEY);
CREATE TABLE Banda(id INTEGER PRIMARY KEY, nombre VARCHAR(50), descripcion VARCHAR(50));
CREATE TABLE Cancion(id INTEGER PRIMARY KEY, nombre VARCHAR(50), duracion FLOAT);
CREATE TABLE Disco(id INTEGER PRIMARY KEY, nombre VARCHAR(50), fecha DATE, sello VARCHAR(25), descripcion VARCHAR(120));
CREATE TABLE Categoria(id INTEGER PRIMARY KEY, nombre VARCHAR(50));
CREATE TABLE Genero(id INTEGER PRIMARY KEY, nombre VARCHAR(50));
/* Relaciones */
CREATE TABLE HasEmail(id INTEGER,email VARCHAR(50),PRIMARY kEY(email), FOREIGN KEY(id) REFERENCES Artista, FOREIGN KEY(email) REFERENCES Email);
CREATE TABLE ArtistaAutorOf(ida INTEGER, idd INTEGER PRIMARY KEY, FOREIGN KEY(ida) REFERENCES Artista, FOREIGN KEY(idd) REFERENCES Disco);
CREATE TABLE TieneCategoria(idcategoria INTEGER, iddisc INTEGER, FOREIGN KEY(idcategoria) REFERENCES Categoria, FOREIGN KEY(iddisc) REFERENCES Disco);
CREATE TABLE CancionEnDisco(idc INTEGER, idd INTEGER, numero_pista INTEGER, FOREIGN KEY(idc) REFERENCES Cancion, FOREIGN KEY(idd) REFERENCES Disco);
CREATE TABLE PerteneceGenero(idg INTEGER, idd INTEGER, FOREIGN KEY(idg) REFERENCES Genero, FOREIGN KEY(idd) REFERENCES Disco);
CREATE TABLE Miembro(idb INTEGER, ida INTEGER, fecha_ingreso DATE, fecha_abandono DATE, FOREIGN KEY(idb) REFERENCES Banda, FOREIGN KEY(ida) REFERENCES Artista);
CREATE TABLE BandaAutorOf(idb INTEGER, idd INTEGER, FOREIGN KEY(idb) REFERENCES Banda, FOREIGN KEY(idd) REFERENCES Disco);
CREATE TABLE ArtistaColabora(idc INTEGER, ida INTEGER, FOREIGN Key(idc) REFERENCES Cancion, FOREIGN KEY(ida) REFERENCES Artista);
CREATE TABLE BandaColabora(idc INTEGER, idb INTEGER, FOREIGN KEY(idc) REFERENCES Cancion, FOREIGN KEY(idb) REFERENCES Banda);