CREATE TABLE Artista(id INTEGER PRIMARY KEY, nombre VARCHAR(50) NOT NULL,edad INTEGER NOT NULL, sexo VARCHAR(50) NOT NULL);
CREATE TABLE Email(email VARCHAR(50) PRIMARY KEY);
CREATE TABLE Banda(id INTEGER PRIMARY KEY, nombre VARCHAR(50), descripcion VARCHAR(50));
CREATE TABLE Cancion(id INTEGER PRIMARY KEY, nombre VARCHAR(50), duracion FLOAT);
CREATE TABLE Disco(id INTEGER PRIMARY KEY, nombre VARCHAR(50), fecha DATE, sello VARCHAR(25), descripcion VARCHAR(120));
CREATE TABLE Categoria(id INTEGER PRIMARY KEY, nombre VARCHAR(50));
CREATE TABLE Genero(id INTEGER PRIMARY KEY, nombre VARCHAR(50));
/* Relaciones */
CREATE TABLE HasEmail(aid INTEGER,email INTEGER,PRIMARY kEY(email), FOREIGN KEY(id) REFERENCES Artista, FOREIGN KEY(aid) REFERENCES Email);
CREATE TABLE ArtistaAutorOf(ida INTEGER, idd INTEGER PRIMARY KEY, FOREIGN KEY(ida) REFERENCES Artista, FOREIGN KEY(idd) REFERENCES Disco);
CREATE TABLE TieneCategoria(idcategoria INTEGER, iddisc INTEGER, FOREIGN KEY(idcategoria) REFERENCES Categoria, FOREIGN KEY(iddisc) REFERENCES Disco);
